# Generated by Django 4.2.4 on 2023-10-09 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadAsset', '0005_alter_uploadasset_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=50, unique=True)),
                ('expiration_duration', models.PositiveIntegerField(choices=[(86400, '1 Day'), (259200, '3 Days'), (604800, '1 Week'), (2592000, '1 Month')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadAsset.uploadasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
