# Generated by Django 4.2.4 on 2023-10-09 06:09

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('share_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedasset',
            name='short_url',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22),
        ),
    ]
